name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install additional packages
        run: |
          set -ex
          apt-get -qy update
          apt-get -qy install m4 pandoc parallel python3-pygments ruby
      - name: Generate the ConTeXt file database
        run: |
          set -ex
          mtxrun --generate
      - name: Install the Markdown package
        run: |
          set -ex
          xetex markdown.ins
          mkdir -p                ~/texmf/tex/luatex/markdown/
          cp -f markdown.lua      ~/texmf/tex/luatex/markdown/
          mkdir -p                ~/texmf/scripts/markdown/
          cp -f markdown-cli.lua  ~/texmf/scripts/markdown/
          mkdir -p                ~/texmf/tex/generic/markdown/
          cp -f markdown.tex      ~/texmf/tex/generic/markdown/
          mkdir -p                ~/texmf/tex/latex/markdown/
          cp -f markdown.sty      ~/texmf/tex/latex/markdown/
          mkdir -p                ~/texmf/tex/context/third/markdown/
          cp -f t-markdown.tex    ~/texmf/tex/context/third/markdown/
      - name: Typeset documentation and example documents
        run: |
          set -ex
          make -j `nproc` all
      - name: Run tests
        run: |
          set -ex
          make test
